// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCvkW9SXsftPiFkePDuj6XM29dzmpOhsU',
    appId: '1:368312545750:web:ab3806693a01072c8af477',
    messagingSenderId: '368312545750',
    projectId: 'midypoint-app',
    authDomain: 'midypoint-app.firebaseapp.com',
    storageBucket: 'midypoint-app.firebasestorage.app',
    measurementId: 'G-3W3WLBQSVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCByIVh1G8ZPRPkOe2dfrP6_ufXUAEbc_w',
    appId: '1:368312545750:android:6331ce2f0b053d3b8af477',
    messagingSenderId: '368312545750',
    projectId: 'midypoint-app',
    storageBucket: 'midypoint-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdfwBVoeH3TUOcpRwqLk1p8nd6FJdu-U',
    appId: '1:368312545750:ios:eaf8289acee3a94c8af477',
    messagingSenderId: '368312545750',
    projectId: 'midypoint-app',
    storageBucket: 'midypoint-app.firebasestorage.app',
    iosBundleId: 'com.example.ali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdfwBVoeH3TUOcpRwqLk1p8nd6FJdu-U',
    appId: '1:368312545750:ios:eaf8289acee3a94c8af477',
    messagingSenderId: '368312545750',
    projectId: 'midypoint-app',
    storageBucket: 'midypoint-app.firebasestorage.app',
    iosBundleId: 'com.example.ali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCvkW9SXsftPiFkePDuj6XM29dzmpOhsU',
    appId: '1:368312545750:web:364d3d532db3afe58af477',
    messagingSenderId: '368312545750',
    projectId: 'midypoint-app',
    authDomain: 'midypoint-app.firebaseapp.com',
    storageBucket: 'midypoint-app.firebasestorage.app',
    measurementId: 'G-JHEVCDP67E',
  );
}
